kind: pipeline
type: exec
name: default

clone:
  depth: 50

steps:
- name: update Drake Docker compose
  environment:
    DOCKER:
      from_secret: orgulho
  commands:
  - echo "teste ${DOCKER}" > teste.txt
  - cat teste.txt