kind: pipeline
type: exec
name: default

clone:
  depth: 50

steps:
- name: update Drake Docker compose
  environment:
    TESTE_PIPELINE:
      from_secret: TESTE
  commands:
  - echo ${TESTE_PIPELINE}