kind: pipeline
type: exec
name: default

clone:
  depth: 50

steps:
- name: update Drake Docker compose
  environment:
    DOCKER:
      from_secret: orgulho
  commands:
  - export DOCKER=DOCKER_VAR
  - echo "$DOCKER_VAR" > teste.txt
  - cat teste.txt

---
kind: secret
name: orgulho
data: hiFG/xoXlIJf1HhO1DU40mCL0s+aGrQjAripPGUj7EmwnR0W+XJuczc=